Fixed ticket 105 - list flirts for company
team-jasmijn/frontend pull request #27
Opened 2023-01-11 09:52 UTC by SilGosker

2023-01-11 09:59 UTC, HUSKUT commented on screens/HomeScreen.tsx
>  type ProfileScreenNavigationProp = NativeStackNavigationProp<
I have fixed this naming issue in my branch

2023-01-11 10:05 UTC, marnixah requested changes

2023-01-11 10:05 UTC, SophiaH67 commented on screens/HomeScreen.tsx
> +  const [flirts, setFlirts] = useState<Flirt[]>();
Initialize with empty array instead of undefined (doesn't ts complain about this?

e.g.

```ts
const [myList, setMyList] = useState<string[]>([])
```

2023-01-11 10:05 UTC, marnixah commented on screens/HomeScreen.tsx
> +        backendFetch<Flirt[]>('GET', 'flirts').then(flirts =>
Fetches should *always* be in a function that gets called *once*. Such as useEffect or an onClick handler

2023-01-11 10:05 UTC, marnixah commented on screens/HomeScreen.tsx
> +            ))}
Comments + make backend return dictionary instead of array

2023-01-11 10:05 UTC, marnixah commented on types/User.ts
> +  role?: 'Moderator' | 'Company' | 'Student';
Maybe extract to enum

```ts
enum Role {
  Moderator = 'Moderator'
  Company = 'Company'
  Student = 'Student'
}

export default Role
```

2023-01-11 10:08 UTC, HUSKUT requested changes

2023-01-11 10:08 UTC, HUSKUT commented on screens/HomeScreen.tsx
> +        backendFetch<User[]>('GET', 'company')
does this endpoint exist in an upcoming branch/pr?

2023-01-16 14:00 UTC, marnixah approved these changes

2023-01-16 14:01 UTC, HUSKUT approved these changes

2023-01-17 10:25 UTC, ironWolf77 approved these changes

2023-01-17 10:25 UTC, merged